name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  carousel_slider: ^5.1.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1

  # Firebase & Auth
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1

  # Networking & APIs
  http: ^1.5.0
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.1

  # State Management & DI
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Navigation
  go_router: ^12.1.1

  # Media
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.5
  injectable_generator: ^2.8.1
  source_gen: ^3.1.0
  analyzer: ^7.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/mock/